services:
  lockercloud:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lockercloud_app
    ports:
      - "8443:8443"
      - "9000:9000"
    environment:
      # HTTP controllers are disabled by default; add 'http' to enable them
      - SPRING_PROFILES_ACTIVE=prod
      - KEYSTORE_PASSWORD=changeit
    volumes:
      - ./filestorage:/app/filestorage
      - ./keystore.p12:/app/keystore.p12:ro
