services:
  lockercloud:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lockercloud_app
    ports:
      - "9000:9000"
    volumes:
      - ./filestorage:/app/filestorage
